# Generated by Django 4.0.5 on 2022-06-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudoapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1024, null=True)),
                ('minimum_order_quantity', models.FloatField(default=1.0)),
                ('todays_price', models.FloatField(null=True)),
                ('offer_price', models.FloatField(null=True)),
                ('measuring_unit', models.CharField(choices=[('10 Milligrams(mg)', '1 Centigram(cg)'), ('10 Centigrams', '1 Decigram (dg)'), ('10 Decigrams', '1 Gram (g)'), ('10 Grams', '1 Dekagram (dag)'), ('10 Dekagrams', '1 Hectogram (hg)'), ('10 Hectograms', '1 Kilogram (kg)'), ('1000 Kilograms', '1 Metric ton (t)')], default='Kg(s)', max_length=100)),
                ('discounted_price', models.FloatField(null=True)),
                ('bulk_price', models.FloatField(blank=True, null=True)),
                ('bulk_qty', models.FloatField(blank=True, null=True)),
                ('available_quantity', models.FloatField(null=True)),
                ('min_available_qty', models.FloatField(default=1.0)),
                ('max_available_qty', models.FloatField(default=models.FloatField(null=True), null=True)),
                ('max_qty_allowed_per_order', models.FloatField(default=None, null=True)),
                ('gst', models.FloatField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('quantityPerCrate', models.FloatField(blank=True, null=True)),
                ('delivery_charge', models.FloatField(default=0.0)),
                ('packingByCrateOrBag', models.CharField(choices=[('Crates and Pallets', 'Crates and Pallets'), ('Crates and Pallets', 'Crates and Pallets'), ('Vacuum Packaging', 'Vacuum Packaging'), ('Preservation Packaging', 'Preservation Packaging'), ('Shock Mount Packaging', 'Shock Mount Packaging')], default='Crate', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
